import streamlit as st
import os
from dotenv import load_dotenv
from scraper import scrape_url
from agent import generate_sales_insights
from pdf_handler import extract_text_from_pdf

# Load environment variables
# I.E. the API Key for Google AI
load_dotenv()

# Set up the basics of the Web page
st.set_page_config(page_title="Sales Agent", page_icon="💼", layout="wide")

st.title("💼 Sales Assistant Agent")
st.markdown("Generate account insights, competitor analysis, and strategy summaries.")

# Sidebar for API Key (optional security measure) or just informational
with st.sidebar:
    st.info("System Status: Ready")
    if os.getenv("GOOGLE_API_KEY"):
        st.success("API Key Detected")
    else:
        st.error("Missing API Key")

# Create the form for the sales rep to fill out
with st.form("input_form"):
    st.header("1. Product & Target Details")
    col1, col2 = st.columns(2)
    # Product Name: What product are you selling?
    # Product Category: This could be one word or a sentence (e.g., "Data Warehousing" 
    #                   or "Cloud Data Platform"). The LLM should identify thecategory 
    #                   from the description.
    with col1:
        product_name = st.text_input("Product Name", placeholder="e.g., Snowflake Data Cloud")
        product_category = st.text_input("Product Category", placeholder="e.g., Cloud Data Platform")
    # Target Customer: Name of the person you are trying to sell to.
    # Company URL: The URL of the company you are targeting. (Use this to derive the     
    #              company  ID and other metadata.)
    with col2:
        target_customer = st.text_input("Target Customer (Name)", placeholder="e.g., John Doe")
        company_url = st.text_input("Target Company URL", placeholder="https://www.target-company.com")

    # Value Proposition: A sentence summarizing the product’s value.   
    value_proposition = st.text_area("Value Proposition", placeholder="Summarize your product's value...")
    
    # Competitors: URLs of competitors (similar to the company URL input)
    st.header("2. Competitor Analysis")
    competitor_urls = st.text_area("Competitor URLs (one per line)", placeholder="https://www.competitor1.com")

    # Submit form
    submitted = st.form_submit_button("Generate Insights")

# Upon submission we have to retrieve the Google AI API Key from the environment variables
# of the app.  Also check to make sure required form fields have values
if submitted:
    if not os.getenv("GOOGLE_API_KEY"):
        st.error("Error: GOOGLE_API_KEY not found in .env file.")
    elif not product_name or not company_url:
        st.warning("Please fill in the Product Name and Target Company URL.")
    else:
        # 1. Scrape Target
        with st.status("Gathering Intelligence...", expanded=True) as status:
            st.write(f"Scraping Target: {company_url}...")
            company_data = scrape_url(company_url)
            
            # 2. Scrape Competitors
            competitor_data_list = []
            if competitor_urls:
                # ... existing competitor logic ...
                urls_list = [url.strip() for url in competitor_urls.split('\n') if url.strip()]
                for url in urls_list:
                    st.write(f"Scraping Competitor: {url}...")
                    data = scrape_url(url)
                    competitor_data_list.append(f"Source: {url}\nContent: {data}")
            
            # 3. Process PDF (NEW)
            product_manual_text = ""
            if uploaded_file:
                st.write("Reading Product Manual...")
                product_manual_text = extract_text_from_pdf(uploaded_file)

            st.write("Thinking...")
            
            # 4. Call AI Agent (Updated Signature)
            insights, model_used = generate_sales_insights(
                product_name, 
                product_category, 
                value_proposition, 
                target_customer, 
                company_data, 
                competitor_data_list,
                product_manual_text # <--- Passing the PDF text
            )
            status.update(label="Analysis Complete!", state="complete", expanded=False)

        # 5. Display Result & Model Name
        st.caption(f"Generated by: **{model_used}**") # <--- Dynamic Announcement
        st.divider()
        st.markdown(insights)